language: node_js
before_install:
- openssl aes-256-cbc -K $encrypted_4684466f091c_key -iv $encrypted_4684466f091c_iv
  -in github_deploy_key.enc -out github_deploy_key -d
- chmod +x ./scripts/compile.sh
script:
- |
  if [ "$TEST_TYPE" = lint ]; then
    npm run lint
  elif [ "$TEST_TYPE" = deploy ]; then
    bash ./scripts/deploy.sh
  fi
env:
  global:
  - ENCRYPTION_LABEL: ffda7dbc26ad
  - COMMIT_AUTHOR_EMAIL: surgesoft@gmail.com
  matrix:
  - TEST_TYPE=lint
  - TEST_TYPE=deploy
node_js:
- stable
